services:
  jilite:
    container_name: jilite
    image: jilite
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - jilite_db:/app/prisma
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proxy-net

volumes:
  jilite_db:

networks:
  proxy-net:
    external: true
